import React from 'react';
import { setupMissing } from '../utils/fieldWorkflow';
const fields=[['jobName','Company name','shared-job-name'],['serialNumberText','Serial number','shared-serial-number'],['siteStreetAddress','Site address','shared-site-address'],['siteCity','City','shared-city'],['siteState','State','shared-state'],['siteZip','ZIP code','shared-zip'],['siteMailingAddress','Mailing address','shared-mailing'],['customerContact','Site contact','shared-contact']];
export default function TripSetupPanel({report,user,onUpdate,onStart,onManage,children,types,onCorrectExisting}) {
 const missing=setupMissing(report,user); const acceptance=report.documents.find(doc=>doc.name==='Acceptance Certificate');
 return <section className="setup-panel space-y-5"><div className="section-heading"><div><p className="eyebrow">Before you head inside</p><h2>Get the trip ready.</h2><p>Confirm the shared details once. Your selected documents reuse them.</p></div><span className="status-pill">{missing.length?'Setup incomplete':'Headers ready'}</span></div>
 {report.inviteMeta?.summary && <p className="import-receipt">Imported: {report.inviteMeta.summary}. Review every value; all fields remain editable.</p>}{children}
 <div className="surface"><label>Trip type<select id="setup-trip-type" value={report.tripType||''} onChange={e=>onUpdate({tripType:e.target.value})}><option value="">Choose trip type</option>{types.map(type=><option key={type}>{type}</option>)}</select></label><p className="text-sm text-slate-600 mt-2">Changing trip type keeps existing pages and work. Use Manage documents to choose applicable pages.</p></div>
 <div className="surface"><h3>Site & contacts</h3><div className="field-grid">{fields.map(([key,label,id])=><label key={key}>{label}<input id={id} value={report.sharedSite?.[key]||''} onChange={e=>onUpdate({sharedSite:{...report.sharedSite,[key]:e.target.value}})}/></label>)}{acceptance && <label>Customer contact<input id="acceptance-customer-contact" value={acceptance.data?.customerContactName||''} onChange={e=>onUpdate({documents:report.documents.map(doc=>doc.id===acceptance.id?{...doc,data:{...doc.data,customerContactName:e.target.value}}:doc)})}/></label>}</div></div>
 <div className="surface"><div className="flex justify-between gap-3 items-center"><h3>Documents for this trip</h3><button onClick={onManage}>Manage documents</button></div><p className="text-sm text-slate-600 mt-2">{report.documents.map(doc=>doc.name).join(' · ')||'No documents selected'}</p></div>
 <div className="surface"><h3>{missing.length?`${missing.length} details need attention`:'Ready to start recording work'}</h3><p className="text-sm text-slate-600">Your setup is saved automatically. You can leave and return at any time.</p><div className="flex flex-wrap gap-2 my-3">{missing.map(item=><button className="missing-link" key={item.label} onClick={()=>{const el=document.querySelector(item.target.selector);el?.scrollIntoView({block:'center',behavior:'smooth'});el?.focus({preventScroll:true});}}>{item.label} →</button>)}</div><button className="primary" disabled={missing.length>0||!report.documents.length} onClick={onStart}>Start report →</button>{onCorrectExisting&&<button className="ml-3" onClick={onCorrectExisting}>Access saved work for correction</button>}</div></section>;
}
